#!/usr/bin/env bash

# Unpack assets from ROM extraction.

# TODO: The packed bins do not depend on their extracted contents yet so modifying these files will do nothing. Add dependencies

# Unpack/move any multi or single asset bins.
tools/unpack_asset.py assets/us/n64_logo_texture.bin
tools/unpack_asset.py assets/us/fonts.bin
tools/unpack_asset.py assets/us/backgrounds.bin
tools/unpack_asset.py assets/us/battle_headers.bin
tools/unpack_asset.py assets/us/common_menu0_ui.bin
tools/unpack_asset.py assets/us/common_menu1_ui.bin
tools/unpack_asset.py assets/us/common_menu2_ui.bin
tools/unpack_asset.py assets/us/area_select_ui.bin
tools/unpack_asset.py assets/us/menu_select_ui.bin
tools/unpack_asset.py assets/us/stadium_select_ui.bin
tools/unpack_asset.py assets/us/title_ui.bin
tools/unpack_asset.py assets/us/52F6D0.bin # unused UI
tools/unpack_asset.py assets/us/battle_portraits.bin
tools/unpack_asset.py assets/us/stadium_models.bin
tools/unpack_asset.py assets/us/5C7A70.bin # unk FRAGMENT
tools/unpack_asset.py assets/us/pokedex_area_model.bin
tools/unpack_asset.py assets/us/sushi_go_round.bin
tools/unpack_asset.py assets/us/order_select_ui.bin
tools/unpack_asset.py assets/us/cup_ball_select_ui.bin
tools/unpack_asset.py assets/us/trade_select_ui.bin
tools/unpack_asset.py assets/us/kids_club_select_ui.bin
tools/unpack_asset.py assets/us/gym_leader_castle_clear_gfx.bin
tools/unpack_asset.py assets/us/rental_rules_ui.bin
tools/unpack_asset.py assets/us/sushi_go_round_sprites.bin
tools/unpack_asset.py assets/us/kids_club_game_ui.bin
tools/unpack_asset.py assets/us/gallery_ui.bin
tools/unpack_asset.py assets/us/album_ui.bin
tools/unpack_asset.py assets/us/6A9750.bin # print UI
tools/unpack_asset.py assets/us/snap_select_ui.bin
tools/unpack_asset.py assets/us/cup_clear_ui.bin
tools/unpack_asset.py assets/us/gb_pak_select_ui.bin
tools/unpack_asset.py assets/us/victory_palace_plate_text.bin
tools/unpack_asset.py assets/us/run_rattata_run_flag_gfx.bin
tools/unpack_asset.py assets/us/kanto_gb_map.bin
tools/unpack_asset.py assets/us/6CA730.bin # unused 15 type BGs
tools/unpack_asset.py assets/us/6E2F90.bin # blank file
tools/unpack_asset.py assets/us/battle_ui.bin
tools/unpack_asset.py assets/us/transfer_pak_error_ui.bin
tools/unpack_asset.py assets/us/6EB340.bin
tools/unpack_asset.py assets/us/6EC4D0.bin
tools/unpack_asset.py assets/us/badge_ui.bin
tools/unpack_asset.py assets/us/gym_leader_castle_ui.bin
# 70D3A0 needs special processing. not a normal asset bin
# 7820E0 isnt a normal asset bin either
tools/unpack_asset.py assets/us/textdata.bin
tools/unpack_asset.py assets/us/798CD0.bin
tools/unpack_asset.py assets/us/snap_mode_ui.bin
tools/unpack_asset.py assets/us/copyright.bin

# Next, decompress all the PERS-SZP files with a Yay0. TODO: Roll these up
# into recursive calls. All of the files within an asset bin SHOULD be the
# same type, but it in theory it isnt guaranteed to be. Does the game ensure
# that? If so, we should be able to safely roll these up.
tools/decompress_persszp.py assets/us/n64_logo_texture/0/file.bin
tools/decompress_persszp.py assets/us/fonts/0/file.bin
tools/decompress_persszp.py assets/us/fonts/1/file.bin
tools/decompress_persszp.py assets/us/fonts/2/file.bin
tools/decompress_persszp.py assets/us/fonts/3/file.bin
tools/decompress_persszp.py assets/us/fonts/4/file.bin
tools/decompress_persszp.py assets/us/fonts/5/file.bin
tools/decompress_persszp.py assets/us/battle_headers/0/file.bin
tools/decompress_persszp.py assets/us/battle_headers/1/file.bin
tools/decompress_persszp.py assets/us/battle_headers/2/file.bin
tools/decompress_persszp.py assets/us/battle_headers/3/file.bin
tools/decompress_persszp.py assets/us/battle_headers/4/file.bin
tools/decompress_persszp.py assets/us/battle_headers/5/file.bin
tools/decompress_persszp.py assets/us/battle_headers/6/file.bin
tools/decompress_persszp.py assets/us/battle_headers/7/file.bin
tools/decompress_persszp.py assets/us/battle_headers/8/file.bin
tools/decompress_persszp.py assets/us/battle_headers/9/file.bin
tools/decompress_persszp.py assets/us/battle_headers/10/file.bin
tools/decompress_persszp.py assets/us/battle_headers/11/file.bin
tools/decompress_persszp.py assets/us/battle_headers/12/file.bin
tools/decompress_persszp.py assets/us/common_menu0_ui/0/file.bin
tools/decompress_persszp.py assets/us/common_menu1_ui/0/file.bin
tools/decompress_persszp.py assets/us/common_menu2_ui/0/file.bin
tools/decompress_persszp.py assets/us/area_select_ui/0/file.bin
tools/decompress_persszp.py assets/us/menu_select_ui/0/file.bin
tools/decompress_persszp.py assets/us/stadium_select_ui/0/file.bin
tools/decompress_persszp.py assets/us/title_ui/0/file.bin
tools/decompress_persszp.py assets/us/52F6D0/0/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/0/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/1/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/2/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/3/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/4/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/5/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/6/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/7/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/8/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/9/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/10/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/11/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/12/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/13/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/14/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/15/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/16/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/17/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/18/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/19/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/20/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/21/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/22/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/23/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/24/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/25/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/26/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/27/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/28/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/29/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/30/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/31/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/32/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/33/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/34/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/35/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/36/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/37/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/38/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/39/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/40/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/41/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/42/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/43/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/44/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/45/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/46/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/47/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/48/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/49/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/50/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/51/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/52/file.bin
tools/decompress_persszp.py assets/us/battle_portraits/53/file.bin
tools/decompress_persszp.py assets/us/stadium_models/0/file.bin
tools/decompress_persszp.py assets/us/stadium_models/1/file.bin
tools/decompress_persszp.py assets/us/stadium_models/2/file.bin
tools/decompress_persszp.py assets/us/stadium_models/3/file.bin
tools/decompress_persszp.py assets/us/stadium_models/4/file.bin
tools/decompress_persszp.py assets/us/stadium_models/5/file.bin
tools/decompress_persszp.py assets/us/stadium_models/6/file.bin
tools/decompress_persszp.py assets/us/stadium_models/7/file.bin
tools/decompress_persszp.py assets/us/stadium_models/8/file.bin
tools/decompress_persszp.py assets/us/stadium_models/9/file.bin
tools/decompress_persszp.py assets/us/stadium_models/10/file.bin
tools/decompress_persszp.py assets/us/stadium_models/11/file.bin
tools/decompress_persszp.py assets/us/stadium_models/12/file.bin
tools/decompress_persszp.py assets/us/stadium_models/13/file.bin
tools/decompress_persszp.py assets/us/stadium_models/14/file.bin
tools/decompress_persszp.py assets/us/stadium_models/15/file.bin
tools/decompress_persszp.py assets/us/stadium_models/16/file.bin
tools/decompress_persszp.py assets/us/stadium_models/17/file.bin
tools/decompress_persszp.py assets/us/5C7A70/0/file.bin
tools/decompress_persszp.py assets/us/pokedex_area_model/0/file.bin
tools/decompress_persszp.py assets/us/sushi_go_round/0/file.bin
tools/decompress_persszp.py assets/us/order_select_ui/0/file.bin
tools/decompress_persszp.py assets/us/cup_ball_select_ui/0/file.bin
tools/decompress_persszp.py assets/us/trade_select_ui/0/file.bin
tools/decompress_persszp.py assets/us/kids_club_select_ui/0/file.bin
tools/decompress_persszp.py assets/us/gym_leader_castle_clear_gfx/0/file.bin
tools/decompress_persszp.py assets/us/rental_rules_ui/0/file.bin
tools/decompress_persszp.py assets/us/sushi_go_round_sprites/0/file.bin
tools/decompress_persszp.py assets/us/kids_club_game_ui/0/file.bin
tools/decompress_persszp.py assets/us/gallery_ui/0/file.bin
tools/decompress_persszp.py assets/us/album_ui/0/file.bin
tools/decompress_persszp.py assets/us/6A9750/0/file.bin
tools/decompress_persszp.py assets/us/snap_select_ui/0/file.bin
tools/decompress_persszp.py assets/us/cup_clear_ui/0/file.bin
tools/decompress_persszp.py assets/us/gb_pak_select_ui/0/file.bin
tools/decompress_persszp.py assets/us/victory_palace_plate_text/0/file.bin
tools/decompress_persszp.py assets/us/run_rattata_run_flag_gfx/0/file.bin
tools/decompress_persszp.py assets/us/kanto_gb_map/0/file.bin
tools/decompress_persszp.py assets/us/6E2F90/0/file.bin
tools/decompress_persszp.py assets/us/battle_ui/0/file.bin
tools/decompress_persszp.py assets/us/transfer_pak_error_ui/0/file.bin
tools/decompress_persszp.py assets/us/6EB340/0/file.bin
tools/decompress_persszp.py assets/us/6EB340/1/file.bin
tools/decompress_persszp.py assets/us/6EB340/2/file.bin
tools/decompress_persszp.py assets/us/6EB340/3/file.bin
tools/decompress_persszp.py assets/us/6EC4D0/0/file.bin
tools/decompress_persszp.py assets/us/badge_ui/0/file.bin
tools/decompress_persszp.py assets/us/gym_leader_castle_ui/0/file.bin
tools/decompress_persszp.py assets/us/798CD0/0/file.bin
tools/decompress_persszp.py assets/us/snap_mode_ui/0/file.bin
tools/decompress_persszp.py assets/us/copyright/0/file.bin

# Extract all PRESJPEG files.
tools/extract_presjpeg.py assets/us/backgrounds/0/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/1/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/2/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/3/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/4/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/5/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/6/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/7/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/8/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/9/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/10/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/11/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/12/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/13/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/14/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/15/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/16/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/17/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/18/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/19/file.bin
tools/extract_presjpeg.py assets/us/backgrounds/20/file.bin
tools/extract_presjpeg.py assets/us/6CA730/0/file.bin
tools/extract_presjpeg.py assets/us/6CA730/1/file.bin
tools/extract_presjpeg.py assets/us/6CA730/2/file.bin
tools/extract_presjpeg.py assets/us/6CA730/3/file.bin
tools/extract_presjpeg.py assets/us/6CA730/4/file.bin
tools/extract_presjpeg.py assets/us/6CA730/5/file.bin
tools/extract_presjpeg.py assets/us/6CA730/6/file.bin
tools/extract_presjpeg.py assets/us/6CA730/7/file.bin
tools/extract_presjpeg.py assets/us/6CA730/8/file.bin
tools/extract_presjpeg.py assets/us/6CA730/9/file.bin
tools/extract_presjpeg.py assets/us/6CA730/10/file.bin
tools/extract_presjpeg.py assets/us/6CA730/11/file.bin
tools/extract_presjpeg.py assets/us/6CA730/12/file.bin
tools/extract_presjpeg.py assets/us/6CA730/13/file.bin
tools/extract_presjpeg.py assets/us/6CA730/14/file.bin
tools/extract_presjpeg.py assets/us/6CA730/15/file.bin