.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.27.0 */

/* Handwritten function */
glabel __LeoBootGame3
/* C910 8000BD10 3C088000 */  lui        $t0, %hi(D_80000000)
/* C914 8000BD14 25080000 */  addiu      $t0, $t0, %lo(D_80000000)
/* C918 8000BD18 25094000 */  addiu      $t1, $t0, 0x4000
/* C91C 8000BD1C 2529FFE0 */  addiu      $t1, $t1, -0x20
/* C920 8000BD20 4080E000 */  mtc0       $zero, $28 /* handwritten instruction */
/* C924 8000BD24 4080E800 */  mtc0       $zero, $29 /* handwritten instruction */
.L8000BD28:
/* C928 8000BD28 BD080000 */  cache      0x08, 0x0($t0) /* handwritten instruction */
/* C92C 8000BD2C 0109082B */  sltu       $at, $t0, $t1
/* C930 8000BD30 1420FFFD */  bnez       $at, .L8000BD28
/* C934 8000BD34 25080020 */   addiu     $t0, $t0, 0x20
/* C938 8000BD38 3C088000 */  lui        $t0, 0x8000
/* C93C 8000BD3C 240A2000 */  addiu      $t2, $zero, 0x2000
/* C940 8000BD40 010A4821 */  addu       $t1, $t0, $t2
/* C944 8000BD44 2529FFF0 */  addiu      $t1, $t1, -0x10
.L8000BD48:
/* C948 8000BD48 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
/* C94C 8000BD4C 0109082B */  sltu       $at, $t0, $t1
/* C950 8000BD50 1420FFFD */  bnez       $at, .L8000BD48
/* C954 8000BD54 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* C958 8000BD58 00800008 */  jr         $a0
/* C95C 8000BD5C 00000000 */   nop
/* C960 8000BD60 00000000 */  nop
/* C964 8000BD64 00000000 */  nop
/* C968 8000BD68 00000000 */  nop
/* C96C 8000BD6C 00000000 */  nop
